In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/house_data.csv", on_bad_lines='skip')

In [ ]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
df.shape

(21613, 21)

In [ ]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
df.drop(['id'],inplace=True,axis=1)

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
df['Date']=pd.to_datetime(df['date'])

In [ ]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014-12-09
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015-02-25
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014-12-09
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015-02-18

In [ ]:
df.drop(['date'],inplace=True,axis=1)

In [ ]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014-12-09
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015-02-25
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014-12-09
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015-02-18

In [ ]:
df['price'].describe()

count    2.161300e+04
mean     5.400881e+05
std      3.671272e+05
min      7.500000e+04
25%      3.219500e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [ ]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

In [ ]:
IQR=Q3-Q1

In [ ]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [ ]:
outliers = df[(df['price'] < lower) | (df['price'] > upper)]

print(outliers)

           price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
5      1225000.0         4       4.50         5420    101930     1.0
21     2000000.0         3       2.75         3050     44867     1.0
49     1350000.0         3       2.50         2753     65005     1.0
69     1325000.0         5       2.25         3200     20158     1.0
125    1450000.0         4       2.75         2750     17789     1.5
...          ...       ...        ...          ...       ...     ...
21568  1700000.0         4       3.50         3830      8963     2.0
21576  3567000.0         5       4.50         4850     10584     2.0
21590  1222500.0         4       3.50         4910      9444     1.5
21597  1575000.0         4       3.25         3410     10125     2.0
21600  1537000.0         5       3.75         4470      8088     2.0

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
5               0     0          3     11        3890           1530
21              0     4          3      9        2330            720
49              1     2          5      9        2165            588
69              0     0          3      8        1600           1600
125             0     0          3      8        1980            770
...           ...   ...        ...    ...         ...            ...
21568           0     0          3     10        3120            710
21576           1     4          3     10        3540           1310
21590           0     0          3     11        3110           1800
21597           0     0          3     10        3410              0
21600           0     0          3     11        4470              0

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
5          2001             0    98053  47.6561 -122.005           4760
21         1968             0    98040  47.5316 -122.233           4110
49         1953             0    98070  47.4041 -122.451           2680
69         1965             0    98004  47.6303 -122.215           3390
125        1914          1992    98004  47.6141 -122.212           3060
...         ...           ...      ...      ...      ...            ...
21568      2014             0    98004  47.5990 -122.197           2190
21576      2007             0    98008  47.5943 -122.110           3470
21590      2007             0    98074  47.6502 -122.066           4560
21597      2007             0    98040  47.5653 -122.223           2290
21600      2008             0    98004  47.6321 -122.200           2780

       sqft_lot15       Date
5          101930 2014-05-12
21          20336 2014-08-26
49          72513 2015-03-11
69          20158 2014-06-12
125         11275 2015-03-02
...           ...        ...
21568       10777 2015-01-30
21576       18270 2015-01-07
21590       11063 2014-05-14
21597       10125 2015-04-21
21600        8964 2014-10-15

[1146 rows x 20 columns]

In [ ]:
print(len(outliers))

1146

In [ ]:


numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

price: 1146 outliers
bedrooms: 546 outliers
bathrooms: 571 outliers
sqft_living: 572 outliers
sqft_lot: 2425 outliers
floors: 0 outliers
waterfront: 163 outliers
view: 2124 outliers
condition: 30 outliers
grade: 1911 outliers
sqft_above: 611 outliers
sqft_basement: 496 outliers
yr_built: 0 outliers
yr_renovated: 914 outliers
zipcode: 0 outliers
lat: 2 outliers
long: 256 outliers
sqft_living15: 544 outliers
sqft_lot15: 2194 outliers

In [ ]:
df[df['bathrooms'] > 10]

Empty DataFrame
Columns: [price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15, Date]
Index: []

In [ ]:
columns = [
    'price',
    'bedrooms',
    'bathrooms',
    'sqft_living',
    'sqft_lot',
    'sqft_above',
    'sqft_basement',
    'lat',
    'long',
    'sqft_living15',
    'sqft_lot15'
]

In [ ]:
for col_name in columns:
    print(f"\nValue counts for {col_name}:")
    print(df[col_name].value_counts().sort_index())

Value counts for price:
price
75000.0      1
78000.0      1
80000.0      1
81000.0      1
82000.0      1
            ..
5350000.0    1
5570000.0    1
6885000.0    1
7062500.0    1
7700000.0    1
Name: count, Length: 4028, dtype: int64

Value counts for bedrooms:
bedrooms
0       13
1      199
2     2760
3     9824
4     6882
5     1601
6      272
7       38
8       13
9        6
10       3
11       1
33       1
Name: count, dtype: int64

Value counts for bathrooms:
bathrooms
0.00      10
0.50       4
0.75      72
1.00    3852
1.25       9
1.50    1446
1.75    3048
2.00    1930
2.25    2047
2.50    5380
2.75    1185
3.00     753
3.25     589
3.50     731
3.75     155
4.00     136
4.25      79
4.50     100
4.75      23
5.00      21
5.25      13
5.50      10
5.75       4
6.00       6
6.25       2
6.50       2
6.75       2
7.50       1
7.75       1
8.00       2
Name: count, dtype: int64

Value counts for sqft_living:
sqft_living
290      1
370      1
380      1
384      1
390      2
        ..
9640     1
9890     1
10040    1
12050    1
13540    1
Name: count, Length: 1038, dtype: int64

Value counts for sqft_lot:
sqft_lot
520        1
572        1
600        1
609        1
635        1
          ..
982998     1
1024068    1
1074218    1
1164794    1
1651359    1
Name: count, Length: 9782, dtype: int64

Value counts for sqft_above:
sqft_above
290     1
370     1
380     1
384     1
390     2
       ..
7880    1
8020    1
8570    1
8860    1
9410    1
Name: count, Length: 946, dtype: int64

Value counts for sqft_basement:
sqft_basement
0       13126
10          2
20          1
40          4
50         11
        ...
3260        1
3480        1
3500        1
4130        1
4820        1
Name: count, Length: 306, dtype: int64

Value counts for lat:
lat
47.1559    1
47.1593    1
47.1622    1
47.1647    1
47.1764    1
          ..
47.7771    2
47.7772    3
47.7774    1
47.7775    3
47.7776    3
Name: count, Length: 5034, dtype: int64

Value counts for long:
long
-122.519    1
-122.515    1
-122.514    1
-122.512    1
-122.511    2
           ..
-121.325    1
-121.321    1
-121.319    1
-121.316    1
-121.315    2
Name: count, Length: 752, dtype: int64

Value counts for sqft_living15:
sqft_living15
399     1
460     2
620     2
670     1
690     2
       ..
5600    1
5610    1
5790    6
6110    1
6210    1
Name: count, Length: 777, dtype: int64

Value counts for sqft_lot15:
sqft_lot15
651       1
659       1
660       1
748       2
750       4
         ..
434728    1
438213    1
560617    1
858132    1
871200    1
Name: count, Length: 8689, dtype: int64

In [ ]:
df['price'].describe()

count    2.161300e+04
mean     5.400881e+05
std      3.671272e+05
min      7.500000e+04
25%      3.219500e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [ ]:
df.nlargest(10,'bedrooms')

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
15870,640000.0,33,1.75,1620,6000,1.0,0,0,5,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700,2014-06-25
8757,520000.0,11,3.00,3000,4960,2.0,0,0,3,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960,2014-08-21
13314,1148000.0,10,5.25,4590,10920,1.0,0,2,3,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400,2014-08-14
15161,650000.0,10,2.00,3610,11914,2.0,0,0,4,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914,2014-10-29
19254,660000.0,10,3.00,2920,3745,2.0,0,0,4,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745,2014-12-29
4096,599999.0,9,4.50,3830,6988,2.5,0,0,3,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291,2014-05-07
4235,700000.0,9,3.00,3680,4400,2.0,0,0,3,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450,2015-01-06
6079,1280000.0,9,4.50,3650,5000,2.0,0,0,3,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000,2014-08-08
8546,450000.0,9,7.50,4050,6504,2.0,0,0,3,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866,2014-08-11
16844,1400000.0,9,4.00,4620,5508,2.5,0,0,3,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320,2015-03-17

In [ ]:
df = df[df['bedrooms'] != 33]

In [ ]:
df[df['bedrooms'] == 33].index

Index([], dtype='int64')

In [ ]:
print(df.index)

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       21603, 21604, 21605, 21606, 21607, 21608, 21609, 21610, 21611, 21612],
      dtype='int64', length=21612)

In [ ]:
df = df.drop(index=15432)

In [ ]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014-12-09
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015-02-25
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014-12-09
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015-02-18

In [ ]:
df.nlargest(10,'bedrooms')

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
8757,520000.0,11,3.00,3000,4960,2.0,0,0,3,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960,2014-08-21
13314,1148000.0,10,5.25,4590,10920,1.0,0,2,3,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400,2014-08-14
15161,650000.0,10,2.00,3610,11914,2.0,0,0,4,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914,2014-10-29
19254,660000.0,10,3.00,2920,3745,2.0,0,0,4,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745,2014-12-29
4096,599999.0,9,4.50,3830,6988,2.5,0,0,3,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291,2014-05-07
4235,700000.0,9,3.00,3680,4400,2.0,0,0,3,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450,2015-01-06
6079,1280000.0,9,4.50,3650,5000,2.0,0,0,3,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000,2014-08-08
8546,450000.0,9,7.50,4050,6504,2.0,0,0,3,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866,2014-08-11
16844,1400000.0,9,4.00,4620,5508,2.5,0,0,3,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320,2015-03-17
18443,934000.0,9,3.00,2820,4480,2.0,0,0,3,7,1880,940,1918,0,98105,47.6654,-122.307,2460,4400,2015-03-13

In [ ]:
columns = ['price','bedrooms','bathrooms','sqft_living','sqft_lot','sqft_above','sqft_basement','sqft_living15','sqft_lot15']

for col in columns:
    print(f"\nTop 20 values for {col}")
    print(df.nlargest(20, col)[[col]])

Top 20 values for price
           price
7252   7700000.0
3914   7062500.0
9254   6885000.0
4411   5570000.0
1448   5350000.0
1315   5300000.0
1164   5110800.0
8092   4668000.0
2626   4500000.0
8638   4489000.0
12370  4208000.0
4149   4000000.0
2085   3850000.0
7035   3800000.0
19017  3800000.0
16302  3710000.0
6508   3650000.0
18482  3650000.0
15255  3640900.0
19148  3635000.0

Top 20 values for bedrooms
       bedrooms
8757         11
13314        10
15161        10
19254        10
4096          9
4235          9
6079          9
8546          9
16844         9
18443         9
1660          8
4035          8
4067          8
6174          8
9077          8
9452          8
10958         8
12885         8
15070         8
15670         8

Top 20 values for bathrooms
       bathrooms
7252        8.00
12777       8.00
9254        7.75
8546        7.50
4024        6.75
8092        6.75
20578       6.50
21506       6.50
14556       6.25
18302       6.25
1315        6.00
4035        6.00
12370       6.00
19148       6.00
21050       6.00
21344       6.00
4411        5.75
6501        5.75
15751       5.75
16773       5.75

Top 20 values for sqft_living
       sqft_living
12777        13540
7252         12050
3914         10040
9254          9890
8092          9640
4411          9200
14556         8670
18302         8020
1164          8010
1448          8000
13411         7880
19858         7850
16773         7730
18477         7710
14032         7620
4024          7480
12370         7440
11871         7420
10373         7400
1315          7390

Top 20 values for sqft_lot
       sqft_lot
1719    1651359
17319   1164794
7647    1074218
7769    1024068
3949     982998
4441     982278
6691     920423
7077     881654
9714     871200
20452    871200
4540     843309
13006    715690
13477    641203
16188    623779
7294     577605
17825    542322
17576    533610
12919    507038
2964     505166
20421    503989

Top 20 values for sqft_above
       sqft_above
12777        9410
9254         8860
7252         8570
18302        8020
13411        7880
19858        7850
3914         7680
11871        7420
18594        7320
1448         6720
16773        6660
11105        6640
20452        6530
8638         6430
21506        6420
13400        6380
20471        6370
2626         6350
10373        6290
6501         6220

Top 20 values for sqft_basement
       sqft_basement
8092            4820
12777           4130
15482           3500
7252            3480
10085           3260
4411            3000
5049            2850
21344           2810
7035            2730
6628            2720
3020            2620
15049           2610
2713            2600
2125            2590
11829           2580
2088            2570
14556           2550
19215           2550
2236            2500
2444            2490

Top 20 values for sqft_living15
       sqft_living15
19858           6210
10373           6110
1123            5790
5451            5790
16430           5790
20563           5790
20830           5790
21540           5790
11871           5610
1530            5600
12713           5500
2713            5380
4967            5340
5561            5330
15828           5220
18266           5200
7458            5170
11517           5110
19531           5080
7035            5070

Top 20 values for sqft_lot15
       sqft_lot15
9714       871200
20452      858132
13464      560617
8664       438213
3801       434728
1719       425581
19156      422967
6691       411962
15620      392040
21431      392040
17659      386812
11183      380279
11564      360000
7294       358934
3536       339332
15557      335289
8765       326097
12669      325393
13006      325393
12754      320890

In [ ]:
df['bathrooms'].value_counts().sort_index()

bathrooms
0.00      10
0.50       4
0.75      72
1.00    3852
1.25       9
1.50    1446
1.75    3047
2.00    1930
2.25    2047
2.50    5379
2.75    1185
3.00     753
3.25     589
3.50     731
3.75     155
4.00     136
4.25      79
4.50     100
4.75      23
5.00      21
5.25      13
5.50      10
5.75       4
6.00       6
6.25       2
6.50       2
6.75       2
7.50       1
7.75       1
8.00       2
Name: count, dtype: int64

In [ ]:
df['bathrooms'].describe()

count    21611.000000
mean         2.114756
std          0.770190
min          0.000000
25%          1.750000
50%          2.250000
75%          2.500000
max          8.000000
Name: bathrooms, dtype: float64

In [ ]:
df.head(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014-12-09

In [ ]:
df['sqft_living'].value_counts().sort_index()

sqft_living
290      1
370      1
380      1
384      1
390      2
        ..
9640     1
9890     1
10040    1
12050    1
13540    1
Name: count, Length: 1038, dtype: int64

In [ ]:
df['sqft_living'].describe()

count    21611.000000
mean      2079.911295
std        918.476957
min        290.000000
25%       1426.000000
50%       1910.000000
75%       2550.000000
max      13540.000000
Name: sqft_living, dtype: float64

In [ ]:
df['sqft_lot'].value_counts().sort_index()

sqft_lot
520        1
572        1
600        1
609        1
635        1
          ..
982998     1
1024068    1
1074218    1
1164794    1
1651359    1
Name: count, Length: 9782, dtype: int64

In [ ]:
df['sqft_lot'].describe()

count    2.161100e+04
mean     1.510767e+04
std      4.142236e+04
min      5.200000e+02
25%      5.040000e+03
50%      7.618000e+03
75%      1.068850e+04
max      1.651359e+06
Name: sqft_lot, dtype: float64

In [ ]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014-12-09
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015-02-25
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014-12-09
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015-02-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,2014-05-21
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,2015-02-23
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,2014-06-23
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,2015-01-16
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,2014-10-15

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15, Date]
Index: []

In [ ]:
df.head(1)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
0,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13

In [ ]:
df.nlargest(10,'Date')

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date
16594,1310000.0,4,2.25,3750,5000,2.0,0,0,5,8,2440,1310,1924,0,98115,47.6747,-122.303,2170,4590,2015-05-27
13053,445500.0,2,1.75,1390,6670,1.0,0,0,3,6,720,670,1941,0,98115,47.6914,-122.308,920,6380,2015-05-24
5637,450000.0,5,2.00,1870,7344,1.5,0,0,3,7,1870,0,1960,0,98007,47.5951,-122.144,1870,7650,2015-05-15
928,359000.0,2,2.75,1370,1140,2.0,0,0,3,8,1080,290,2009,0,98133,47.7052,-122.343,1370,1090,2015-05-14
6197,1695000.0,5,3.00,3320,5354,2.0,0,0,3,9,3320,0,2004,0,98103,47.6542,-122.331,2330,4040,2015-05-14
7224,456500.0,4,2.50,2580,11780,2.0,0,0,3,9,2580,0,2003,0,98038,47.3658,-122.040,2410,8403,2015-05-14
7898,183000.0,3,1.00,1170,7320,1.0,0,0,3,7,1170,0,1962,0,98188,47.4685,-122.282,2040,7320,2015-05-14
11560,360000.0,4,2.50,2020,7289,2.0,0,0,3,7,2020,0,1994,0,98031,47.4010,-122.171,2090,7259,2015-05-14
12635,335000.0,3,2.00,1410,44866,1.0,0,0,4,7,1410,0,1985,0,98023,47.3273,-122.370,2950,29152,2015-05-14
15811,440000.0,5,2.00,1430,5600,1.5,0,0,3,6,1430,0,1947,0,98118,47.5192,-122.266,1860,5980,2015-05-14

In [ ]:
df['house age'] = df['Date'].dt.year - df['yr_built']

In [ ]:
df.head(1)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Date,house age
0,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,...,0,1955,0,98178,47.5112,-122.257,1340,5650,2014-10-13,59

In [ ]:
df['is_renovated'] = (df['yr_renovated'] > 0).astype(int)

In [ ]:
df['total_rooms'] = df['bedrooms'] + df['bathrooms']

In [ ]:
df['total_sqft'] = df['sqft_above'] + df['sqft_basement']

In [ ]:
df.head(1)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,zipcode,lat,long,sqft_living15,sqft_lot15,Date,house age,is_renovated,total_rooms,total_sqft
0,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,...,98178,47.5112,-122.257,1340,5650,2014-10-13,59,0,4.0,1180

In [ ]:
df.tail(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,zipcode,lat,long,sqft_living15,sqft_lot15,Date,house age,is_renovated,total_rooms,total_sqft
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,...,98027,47.5345,-122.069,1410,1287,2015-01-16,11,0,5.50,1600
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,...,98144,47.5941,-122.299,1020,1357,2014-10-15,6,0,2.75,1020

In [ ]:
df['floors'].value_counts().sort_index()

floors
1.0    10679
1.5     1910
2.0     8240
2.5      161
3.0      613
3.5        8
Name: count, dtype: int64

In [ ]:
df['floors' ].describe()

count    21611.000000
mean         1.494308
std          0.539992
min          1.000000
25%          1.000000
50%          1.500000
75%          2.000000
max          3.500000
Name: floors, dtype: float64

In [ ]:
X=df.drop(['price', 'Date'],axis=1)
y=df['price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
model = RandomForestRegressor(n_estimators=1000, random_state=42)

In [ ]:
#df.drop('Date', axis=1, inplace=True)

In [ ]:
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [ ]:
print(X_train.dtypes)

bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
house age          int64
is_renovated       int64
total_rooms      float64
total_sqft         int64
dtype: object

In [ ]:
df.drop('Date', axis=1, inplace=True)

In [ ]:
df.head(1)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,house age,is_renovated,total_rooms,total_sqft
0,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,...,0,98178,47.5112,-122.257,1340,5650,59,0,4.0,1180

It appears the model was not fitted before attempting to score it, which caused the `NotFittedError`. Let's re-fit the model to resolve this.

In [ ]:
print(X.select_dtypes(exclude=['int64', 'float64']).columns)

Index([], dtype='object')

In [ ]:
model.score(X_test,y_test)

0.8823209609817164

In [ ]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
xgb.score(X_train, y_train)

0.9635927428523912

In [ ]:
xgb.score(X_test,y_test)

0.9033957787239814

In [ ]:
import pickle

pickle.dump(xgb, open("house_price_model.pkl", "wb"))

In [ ]:
!ls

house_data.csv	house_price_model.pkl  sample_data

In [ ]:
%%writefile app.py

Writing app.py

In [ ]:
from google.colab import files
files.download("app.py")

In [ ]:
from google.colab import files
files.download("house_price_model.pkl")